project:
  type: website
  output-dir: docs

website:
  title: "Geographic & Remote Work Analysis"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: introduction.qmd
        text: "Introduction"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: RandomForest.ipynb
        text: "Random Forest"
      - href: about.qmd
        text: "About"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    csl: csl/econometrica.csl

execute:
  echo: true
  eval: true
  code-fold: true
