project:
  type: website
  output-dir: docs

website:
  title: "Geographic & Remote Work Analysis"
  navbar:
  left:
    - href: index.qmd
      text: "Home"
    - href: introduction.qmd
      text: "Introduction"
    - href: data_cleaning.qmd/ipynb
      text: "Data Cleaning & Exploration"
    - href: eda.qmd/ipynb
      text: "Exploratory Data Analysis"
    - href: skill_gap_analysis.qmd
      text: "Skill Gap Analysis"
    - href: ml_methods.qmd/ipynb
      text: "ML Methods"
    - href: nlp_methods.qmd/ipynb
      text: "NLP Methods"
    - href: about.qmd
      text: "About"

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    csl: csl/econometrica.csl