project:
  type: website
  output-dir: docs

website:
  title: "Geographic & Remote Work Analysis"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: introduction.qmd
        text: "Introduction"
      - href: geographic_trends.qmd
        text: "Geographic Trends"
      - href: remote_work_trends.qmd
        text: "Remote Work Trends"
      - href: tech_hubs_analysis.qmd
        text: "Tech Hubs Analysis"
      - href: urban_rural_comparison.qmd
        text: "Urban vs Rural"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd
        text: "ML Methods"
      - href: nlp_methods.qmd
        text: "NLP Methods"
      - href: about.qmd
        text: "About"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    csl: csl/econometrica.csl

execute:
  echo: true
  eval: true
  code-fold: true
